# Generated by Django 6.1.1 on 2026-09-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0003_game_away_starting_pitcher_and_more'),
        ('tving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvingScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fetched_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('empty', 'Empty'), ('pending', 'Pending'), ('error', 'Error')], max_length=8)),
                ('game_count', models.PositiveSmallIntegerField()),
                ('game_codes', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TvingPlayer',
            fields=[
                ('external_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('positions', models.JSONField(default=list)),
                ('back_number', models.CharField(blank=True, max_length=20)),
                ('join_date', models.CharField(blank=True, max_length=40)),
                ('birth_date', models.CharField(blank=True, max_length=40)),
                ('body', models.JSONField(default=list)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('draft_order', models.CharField(blank=True, max_length=100)),
                ('team_color', models.CharField(blank=True, max_length=20)),
                ('team_logo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('season_title', models.CharField(blank=True, max_length=80)),
                ('career_title', models.CharField(blank=True, max_length=80)),
                ('profile_source_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('profile_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('identity_source_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('identity_last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tving_players', to='baseball.team')),
            ],
        ),
        migrations.CreateModel(
            name='TvingTeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fetched_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_code', models.CharField(max_length=2, unique=True)),
                ('short_name', models.CharField(max_length=30)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('background_image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('season_title', models.CharField(max_length=80)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tving_profile', to='baseball.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TvingPlayerCareerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fetched_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('season_label', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=80)),
                ('columns', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_records', to='tving.tvingplayer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'position'), name='uq_tving_player_career_record')],
            },
        ),
        migrations.CreateModel(
            name='TvingPlayerSeasonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fetched_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.PositiveSmallIntegerField()),
                ('record_kind', models.CharField(choices=[('pitcher', 'Pitcher ranking'), ('hitter', 'Hitter ranking'), ('detail', 'Player detail')], max_length=16)),
                ('record_key', models.CharField(max_length=60)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('value', models.CharField(blank=True, max_length=60)),
                ('rank_label', models.CharField(blank=True, max_length=40, null=True)),
                ('is_first_rank', models.BooleanField(default=False)),
                ('metrics', models.JSONField(default=dict)),
                ('graphs', models.JSONField(default=list)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_records', to='tving.tvingplayer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'season', 'record_kind', 'record_key'), name='uq_tving_player_season_record')],
            },
        ),
        migrations.CreateModel(
            name='TvingTeamRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fetched_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('pitcher', 'Pitcher'), ('infielder', 'Infielder'), ('outfielder', 'Outfielder'), ('catcher', 'Catcher')], max_length=16)),
                ('back_number', models.CharField(blank=True, max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_memberships', to='tving.tvingplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tving_roster', to='baseball.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'player'), name='uq_tving_team_roster')],
            },
        ),
        migrations.CreateModel(
            name='TvingTeamSeasonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fetched_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('main', 'Main'), ('box', 'Box')], max_length=8)),
                ('title', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=60)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tving_season_records', to='baseball.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'season', 'category', 'title'), name='uq_tving_team_season_record')],
            },
        ),
        migrations.CreateModel(
            name='TvingTeamTopPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fetched_at', models.DateTimeField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_type', models.CharField(choices=[('pitcher', 'Pitcher'), ('hitter', 'Hitter')], max_length=8)),
                ('category', models.CharField(max_length=40)),
                ('rank', models.PositiveSmallIntegerField()),
                ('value', models.CharField(blank=True, max_length=40)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_top_records', to='tving.tvingplayer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tving_top_players', to='baseball.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'player', 'athlete_type', 'category'), name='uq_tving_team_top_player')],
            },
        ),
    ]
