# Generated by Django 6.1.1 on 2026-09-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tving', '0002_tvingscheduleday_tvingplayer_tvingteamprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvingplayer',
            name='career_positions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tvingplayer',
            name='detail_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvingplayer',
            name='detail_record_keys',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='tvingplayer',
            name='detail_source_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tvingteamprofile',
            name='roster_codes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='tvingteamprofile',
            name='top_keys',
            field=models.JSONField(default=dict),
        ),
    ]
