# Generated by Django 6.1.1 on 2026-09-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_player_teamprofile_playercareerrecord_and_more'),
        ('tving', '0003_tvingplayer_career_positions_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=[
        migrations.RemoveField(
            model_name='tvingplayer',
            name='team',
        ),
        migrations.RemoveConstraint(
            model_name='tvingplayercareerrecord',
            name='uq_tving_player_career_record',
        ),
        migrations.RemoveConstraint(
            model_name='tvingplayerseasonrecord',
            name='uq_tving_player_season_record',
        ),
        migrations.RemoveField(
            model_name='tvingteamprofile',
            name='team',
        ),
        migrations.RemoveConstraint(
            model_name='tvingteamroster',
            name='uq_tving_team_roster',
        ),
        migrations.RemoveConstraint(
            model_name='tvingteamseasonrecord',
            name='uq_tving_team_season_record',
        ),
        migrations.RemoveConstraint(
            model_name='tvingteamtopplayer',
            name='uq_tving_team_top_player',
        ),
        migrations.RemoveField(
            model_name='tvingplayercareerrecord',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tvingplayerseasonrecord',
            name='player',
        ),
        migrations.DeleteModel(
            name='TvingTeamProfile',
        ),
        migrations.RemoveField(
            model_name='tvingteamroster',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tvingteamroster',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tvingteamseasonrecord',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tvingteamtopplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tvingteamtopplayer',
            name='team',
        ),
        migrations.DeleteModel(
            name='TvingPlayerCareerRecord',
        ),
        migrations.DeleteModel(
            name='TvingPlayerSeasonRecord',
        ),
        migrations.DeleteModel(
            name='TvingTeamRoster',
        ),
        migrations.DeleteModel(
            name='TvingTeamSeasonRecord',
        ),
        migrations.DeleteModel(
            name='TvingPlayer',
        ),
        migrations.DeleteModel(
            name='TvingTeamTopPlayer',
        ),
    ])]
