# Generated by Django 6.1.1 on 2026-09-16 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_scheduleday_providersnapshot'),
        ('tving', '0004_remove_tvingplayer_team_and_more'),
    ]

    operations = [migrations.SeparateDatabaseAndState(state_operations=[
        migrations.DeleteModel(
            name='TvingScheduleDay',
        ),
        migrations.RemoveIndex(
            model_name='tvingsnapshot',
            name='tving_resource_idx',
        ),
        migrations.RemoveConstraint(
            model_name='tvingsnapshot',
            name='uq_tving_snapshot_resource',
        ),
        migrations.RemoveConstraint(
            model_name='tvingsnapshot',
            name='ck_tving_snapshot_identity',
        ),
        migrations.DeleteModel(
            name='TvingSnapshot',
        ),
    ])]
