# Generated by Django 6.1.1 on 2026-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_load_baseball_csv_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_starting_pitcher',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_starting_pitcher',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='source',
            field=models.CharField(default='csv', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='source_away_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='game',
            name='source_away_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='source_external_code',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='source_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='source_home_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='game',
            name='source_home_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='source_stadium_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='game',
            name='source_status_label',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='batting_average',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='era',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='last_ten',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='played',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='source',
            field=models.CharField(default='csv', max_length=16),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='source_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='win_rate',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='standinghistory',
            name='winning_streak',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='source',
            field=models.CharField(default='csv', max_length=16),
        ),
        migrations.AddField(
            model_name='team',
            name='source_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
