# Generated by Django 6.1.1 on 2026-09-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_scheduleday_providersnapshot'),
        ('tving', '0005_delete_tvingscheduleday_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='player',
            table=None,
        ),
        migrations.AlterModelTable(
            name='playercareerrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='playerseasonrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='providersnapshot',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scheduleday',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teamprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teamroster',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teamseasonrecord',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teamtopplayer',
            table=None,
        ),
    ]
